---
# tasks file for base

- name: Update apt
  become: True
  apt:
    update_cache: yes
    state: present
  tags:
    - install
    - core

- name: Update software
  become: True
  apt:
    upgrade: yes
  tags:
    - install
    - core

- name: Install gpg
  become: True
  ansible.builtin.apt:
    name: gpg
    state: latest
  tags:
    - install
    - core
    - gpg
    - neomutt

- name: Install Curl
  become: True
  ansible.builtin.apt:
    name: curl
    state: latest
  tags:
    - install
    - core
    - curl

- name: Install Git
  become: True
  ansible.builtin.apt:
    name: git
    state: latest
  tags:
    - install
    - core
    - git

- name: Install Kitty
  become: True
  ansible.builtin.apt:
    name: kitty
    state: latest
  tags:
    - install
    - core
    - Kitty

- name: Install R
  community.general.homebrew:
    name: R
    state: latest
  tags:
    - install
    - core
    - R

# - name: Install Rstudio
#   community.general.homebrew:
#     name: homebrew/cask-versions/rstudio-daily
#     state: latest
#   tags:
#     - install
#     - core
#     - R
#
- name: Install fzf
  become: True
  ansible.builtin.apt:
    name: fzf
    state: latest
  tags:
    - install
    - core
    - fzf

- name: Install glances
  community.general.homebrew:
    name: glances
    state: latest
  tags:
    - install
    - core
    - glances

- name: Install xclip
  become: True
  ansible.builtin.apt:
    name: xclip
    state: latest
  tags:
    - install
    - core
    - xclip

- name: Install htop
  become: True
  ansible.builtin.apt:
    name: htop
    state: latest
  tags:
    - install
    - core
    - htop

- name: Install Ripgrep
  become: True
  ansible.builtin.apt:
    name: ripgrep
    state: latest
  tags:
    - install
    - core
    - Ripgrep

- name: Install fd
  become: True
  ansible.builtin.apt:
    name: fd-find
    state: latest
  tags:
    - install
    - core
    - fd

- name: Install bat
  become: True
  ansible.builtin.apt:
    name: bat
    state: latest
  tags:
    - install
    - core
    - bat

- name: Install glow
  community.general.homebrew:
    name: glow
    state: latest
  tags:
    - install
    - core
    - glow

- name: Install golang
  become: True
  ansible.builtin.apt:
    name: 
      - golang
    state: latest
  tags:
    - install
    - core
    - golang

- name: Install rust
  community.general.homebrew:
    name: 
      - rust
    state: latest
  tags:
    - install
    - core
    - rust

- name: Install ruby
  become: True
  ansible.builtin.apt:
    name: 
      - ruby
      - ruby-dev
    state: latest
  tags:
    - install
    - core
    - ruby

# - name: Install prerequisites for Wally
#   become: True
#   ansible.builtin.apt:
#     name: libusb-1.0.0-dev
#     state: present
#   tags:
#     - install
#     - core
#     - ruby

- name: Install Zathura
  become: True
  ansible.builtin.apt:
    name: 
      - zathura
    state: latest
  tags:
    - install
    - core
    - zathura

