---
# tasks file for base

- name: Update apt
  become: True
  apt:
    update_cache: yes
    state: present
  tags:
    - install
    - core

- name: Update software
  become: True
  apt:
    upgrade: yes
  tags:
    - install
    - core

- name: Install gpg
  become: True
  ansible.builtin.apt:
    name: gpg
    state: latest
  tags:
    - install
    - core
    - gpg
    - neomutt

- name: Install Curl
  become: True
  ansible.builtin.apt:
    name: curl
    state: latest
  tags:
    - install
    - core
    - curl

- name: Install Git
  become: True
  ansible.builtin.apt:
    name: git
    state: latest
  tags:
    - install
    - core
    - git

- name: Install R
  ansible.builtin.homebrew:
    name: R
    state: latest
  tags:
    - install
    - core
    - R

- name: Install fzf
  become: True
  ansible.builtin.apt:
    name: fzf
    state: latest
  tags:
    - install
    - core
    - fzf

- name: Install glances
  ansible.builtin.homebrew:
    name: glances
    state: latest
  tags:
    - install
    - core
    - glances

- name: Install htop
  become: True
  ansible.builtin.apt:
    name: htop
    state: latest
  tags:
    - install
    - core
    - htop

