---

- name: Install docker requisites
  become: true
  ansible.builtin.apt:
    name:
      - lsb-release
      - ca-certificates
      - curl
      - gnupg
    state: present
  tags:
    - install
    - core
    - docker

- name: Docker import GPG keyrings
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  tags:
    - install
    - docker

- name: Docker PPA setting
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - docker
    - install

- name: Install Docker engine
  become: true
  ansible.builtin.apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    update_cache: yes
    state: latest
  tags:
    - install
    - docker

- name: Install Lazydocker
  community.general.homebrew:
    name: Lazydocker
    state: latest
  tags:
    - install
    - docker

