---

# neomutt
- name: Install isync
  community.general.homebrew:
    name: isync
    state: present

- name: Install msmtp
  community.general.homebrew:
    name: msmtp
    state: present

- name: Install abook
  community.general.homebrew:
    name: abook
    state: present

- name: Install neomutt
  community.general.homebrew:
    name: neomutt
    state: present

- name: Install lynx
  become: true
  ansible.builtin.apt:
    name: lynx
    state: present

- name: Clone neomutt configuration
  ansible.builtin.git:
    repo: gogs@ihpe-249.univ-perp.fr:cristian/neomutt.git
    dest: "{{ lookup('env', 'HOME') }}/src/gogs/neomutt"
    clone: yes
    update: yes

- name: Install neomutt configuration
  ansible.builtin.command: chdir="{{ lookup('env', 'HOME') }}/src/gogs/neomutt" ./install.sh

- name: Install urlscan
  ansible.builtin.pip:
    name: urlscan

- name: Install vdirsyncer & khal
  community.general.homebrew:
    name: 
      - vdirsyncer
      - khal
    state: present

