---

# neomutt
- name: Install isync
  ansible.builtin.homebrew:
    name: isync
    state: present

- name: Install msmtp
  ansible.builtin.homebrew:
    name: msmtp
    state: present

- name: Install abook
  ansible.builtin.homebrew:
    name: abook
    state: present

- name: Install neomutt
  ansible.builtin.homebrew:
    name: neomutt
    state: present

- name: Install lynx
  become: true
  ansible.builtin.apt:
    name: lynx
    state: present

- name: Clone neomutt configuration
  ansible.builtin.git:
    repo: gogs@ihpe-249.univ-perp.fr:cristian/neomutt.git
    dest: "{{ lookup('env', 'HOME') }}/src/gogs/neomutt"
    clone: yes
    update: yes

- name: Install neomutt configuration
  ansible.builtin.command: chdir="{{ lookup('env', 'HOME') }}/src/gogs/neomutt" ./install.sh
