---
# tasks file for neovim

- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: latest
    options: HEAD
  tags:
    - neovim

- name: Install Lua
  community.general.homebrew:
    name: 
      - lua
      - luarocks
    state: latest

- name: Install python package for neovim
  ansible.builtin.pip:
    name: pynvim

- name: Install Black formatter
  ansible.builtin.pip:
    name: 
      - black
      - black[jupyter]


- name: Install config
  ansible.builtin.git:
    repo: git@github.com:cche/nvim.git
    dest: "{{ lookup('env', 'HOME') }}/src/github/nvim"
  tags:
    - neovim
    - dotfiles

- name: Link neovim configuration
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/src/github/nvim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: link

- name: Install python packages for magma
  ansible.builtin.pip:
    name: 
      - jupyter-client
      - ueberzug
      - Pillow
      - cairosvg
      - pnglatex
      - plotly
      - kaleido
  tags:
    - neovim
    - magma

- name: Install node.js provider
  ansible.builtin.shell: npm install -g neovim
